import '../styles/global.css'
import { Navigation } from '../shared/navigation/Navigation';
import { Footer } from '../shared/footer/Footer';


export const metadata = {
  title: 'SMART BLOG',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation></Navigation>
          {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
